/**
 * Represents a player imported from RTSports.
 * This object is intentionally UI-agnostic so it can be shared
 * between the extension, optimizer, and React application.
 */

export type RosterGroup =
  | "starter"
  | "bench"
  | "ir"
  | "taxi"
  | "unknown";

export interface LeaguePlayer {
  /** RTSports Player ID */
  id: number;

  /** Full player name */
  name: string;

  /** Current fantasy roster location */
  rosterGroup: RosterGroup;

  /** Slot currently occupied (QB, WR, FLEX, etc.) */
  lineupSlot: string;

  /** Natural position */
  position: string;

  /** NFL team abbreviation */
  nflTeam: string;

  /** Opponent (ex: @DAL or KC) */
  opponent: string | null;

  /** Bye week */
  byeWeek: number | null;

  /** Injury designation (Q, O, IR, etc.) */
  injury: string | null;

  /** RTSports projected fantasy points */
  projection: number | null;

  /** Season average fantasy points */
  averagePoints: number | null;

  /** Current season total */
  seasonPoints: number | null;

  /** Fantasy team name */
  fantasyTeam: string | null;

  /** Headshot URL */
  headshot: string | null;

  /** Percentage of leagues rostered */
  rosterPercent: number | null;

  /** Percentage of leagues started */
  startPercent: number | null;

  /** Weekly fantasy point history */
  weeklyPoints: Record<number, number>;

  /**
   * Calculated later by Fantasy Edge
   */
  adjustedProjection?: number;

  /**
   * 0-100 confidence score
   */
  confidence?: number;

  /**
   * Recommendation generated by optimizer
   */
  recommendation?: "START" | "BENCH";

  /**
   * Why Fantasy Edge chose this player.
   * Displayed only in the player popup.
   */
  reasons?: string[];
}