import { scoreAmdFflStatRow } from '../shared/scoring/scoring-engine';
import { AMDFFL_SCORING_VERSION } from '../shared/scoring/amdffl-2026';

export type IntelligenceEnv = { DB: D1Database };

type CsvRow = Record<string, string>;
type RosterPlayer = { name?: string; position?: string; nflTeam?: string; rosterGroup?: string };
type WeeklySample = { week: number; points: number; team?: string };
type GameContext = { opponent?: string; gameDate?: string; homeAway?: 'home' | 'away' };
type MatchupContext = { multiplier: number; ratio: number; sample: number; source: '2025' | '2026' | 'blended' };
type Projection = { playerKey:string; name:string; position:string; team:string; projection:number|null; confidence:number; trend:'up'|'down'|'steady'|'unknown'; reasons:string[]; sourceGames:number; depthRank?:number; opponent?:string };

const MODEL_VERSION='fe-2026.4';
const NFLVERSE='https://github.com/nflverse/nflverse-data/releases/download';
const SCHEDULE_URL='https://raw.githubusercontent.com/nflverse/nfldata/master/data/games.csv';

export async function ensureIntelligenceSchema(db:D1Database){await db.batch([
 db.prepare(`CREATE TABLE IF NOT EXISTS intelligence_runs (id INTEGER PRIMARY KEY AUTOINCREMENT,started_at TEXT NOT NULL,completed_at TEXT,status TEXT NOT NULL,source_summary TEXT,player_count INTEGER NOT NULL DEFAULT 0,message TEXT)`),
 db.prepare(`CREATE TABLE IF NOT EXISTS player_intelligence (player_key TEXT PRIMARY KEY,display_name TEXT NOT NULL,position TEXT,nfl_team TEXT,projection REAL,confidence REAL NOT NULL,trend TEXT NOT NULL,reasons_json TEXT NOT NULL,source_games INTEGER NOT NULL DEFAULT 0,model_version TEXT NOT NULL,updated_at TEXT NOT NULL)`),
 db.prepare(`CREATE TABLE IF NOT EXISTS projection_snapshots (id INTEGER PRIMARY KEY AUTOINCREMENT,run_id INTEGER NOT NULL,player_key TEXT NOT NULL,display_name TEXT NOT NULL,position TEXT,nfl_team TEXT,projection REAL,confidence REAL NOT NULL,trend TEXT NOT NULL,reasons_json TEXT NOT NULL,model_version TEXT NOT NULL,created_at TEXT NOT NULL)`),
 db.prepare(`CREATE INDEX IF NOT EXISTS idx_projection_snapshots_player ON projection_snapshots(player_key,created_at DESC)`),
 db.prepare(`CREATE INDEX IF NOT EXISTS idx_intelligence_runs_started ON intelligence_runs(started_at DESC)`)
]);}

function normalizeName(v:string){return v.toLowerCase().replace(/\b(jr|sr|ii|iii|iv)\.?\b/g,'').replace(/[^a-z0-9]/g,'').trim()}
function playerKey(n:string,p=''){return `${normalizeName(n)}:${p.toUpperCase()}`}

function parseCsv(text:string):CsvRow[]{const rows:string[][]=[];let row:string[]=[];let field='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'&&quoted&&next==='"'){field+='"';i++}else if(ch==='"')quoted=!quoted;else if(ch===','&&!quoted){row.push(field);field=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(field);field='';if(row.some(v=>v.length))rows.push(row);row=[]}else field+=ch}if(field.length||row.length){row.push(field);if(row.some(v=>v.length))rows.push(row)}if(rows.length<2)return[];const h=rows[0].map(x=>x.trim());return rows.slice(1).map(v=>Object.fromEntries(h.map((x,i)=>[x,v[i]??''])))}
async function fetchCsv(url:string){const r=await fetch(url,{headers:{'user-agent':'FantasyEdge/0.1'}});if(!r.ok)throw new Error(`${r.status} fetching ${url}`);return parseCsv(await r.text())}
async function optionalCsv(url:string){try{return await fetchCsv(url)}catch{return[]}}

function num(r:CsvRow,...keys:string[]){for(const k of keys){const v=Number(r[k]);if(r[k]!==undefined&&r[k]!==''&&Number.isFinite(v))return v}return 0}
function displayName(r:CsvRow){return r.player_display_name||r.player_name||r.full_name||r.display_name||r.name||''}
const scoreCache=new WeakMap<CsvRow,Map<string,number>>();
function fantasyPoints(r:CsvRow,p:string){const pos=p.toUpperCase();let byPosition=scoreCache.get(r);if(!byPosition){byPosition=new Map<string,number>();scoreCache.set(r,byPosition)}const cached=byPosition.get(pos);if(cached!==undefined)return cached;const points=scoreAmdFflStatRow(r,pos).points;byPosition.set(pos,points);return points}
const avg=(v:number[])=>v.length?v.reduce((a,b)=>a+b,0)/v.length:0;

function trendFor(s:WeeklySample[]){if(s.length<4)return'unknown' as const;const x=[...s].sort((a,b)=>a.week-b.week),recent=avg(x.slice(-3).map(y=>y.points)),prior=avg(x.slice(-6,-3).map(y=>y.points));if(!prior)return'steady' as const;if(recent>=prior*1.12)return'up' as const;if(recent<=prior*.88)return'down' as const;return'steady' as const}

function buildSamples(rows:CsvRow[],p:RosterPlayer){const key=normalizeName(p.name??''),pos=(p.position??'').toUpperCase();return rows.filter(r=>normalizeName(displayName(r))===key).filter(r=>!r.position||!pos||r.position.toUpperCase()===pos||['DL','DB'].includes(pos)).filter(r=>!r.season_type||r.season_type==='REG').map(r=>({week:num(r,'week'),points:fantasyPoints(r,pos),team:r.recent_team||r.team||r.team_abbr})).filter(s=>Number.isFinite(s.points))}

function depthContext(p:RosterPlayer,rows:CsvRow[]){const name=normalizeName(p.name??''),team=(p.nflTeam??'').toUpperCase(),m=rows.filter(r=>normalizeName(displayName(r))===name&&(!team||!r.team||r.team.toUpperCase()===team)).sort((a,b)=>String(b.dt||'').localeCompare(String(a.dt||''))),r=m[0];if(!r)return{};const rank=num(r,'pos_rank','depth_team');return{depthRank:rank||undefined,depthSlot:r.pos_slot||r.pos_name||r.depth_position||undefined,depthDate:r.dt||undefined}}

function nextGame(team:string,rows:CsvRow[]):GameContext|undefined{if(!team)return;const today=new Date().toISOString().slice(0,10),c=rows.filter(r=>String(r.season)==='2026'&&(!r.game_type||r.game_type==='REG')).filter(r=>r.home_team===team||r.away_team===team).filter(r=>(r.gameday||r.game_date||'')>=today).sort((a,b)=>String(a.gameday||a.game_date||'').localeCompare(String(b.gameday||b.game_date||''))),r=c[0];if(!r)return;const home=r.home_team===team;return{opponent:home?r.away_team:r.home_team,gameDate:r.gameday||r.game_date,homeAway:home?'home':'away'}}

function opponentFromStat(r:CsvRow){return (r.opponent_team||r.opponent||r.opponent_abbr||'').toUpperCase()}
function normalizedPosition(p:string){const pos=p.toUpperCase();if(['DE','DT'].includes(pos))return'DL';if(['CB','S'].includes(pos))return'DB';return pos}
function matchupFromRows(rows:CsvRow[],opponent:string,position:string){const pos=normalizedPosition(position);if(!opponent||!pos||pos==='HC')return null;const eligible=rows.filter(r=>(!r.season_type||r.season_type==='REG')).filter(r=>normalizedPosition(r.position||'')===pos).map(r=>({opp:opponentFromStat(r),points:fantasyPoints(r,pos)})).filter(x=>x.opp&&Number.isFinite(x.points));const against=eligible.filter(x=>x.opp===opponent).map(x=>x.points);const league=eligible.map(x=>x.points);if(against.length<6||league.length<50)return null;const leagueAvg=avg(league);if(leagueAvg<=0)return null;return{ratio:avg(against)/leagueAvg,sample:against.length}}
function matchupContext(opponent:string,position:string,s25:CsvRow[],s26:CsvRow[]):MatchupContext|undefined{const prior=matchupFromRows(s25,opponent,position),current=matchupFromRows(s26,opponent,position);if(!prior&&!current)return;let ratio=1,sample=0,source:'2025'|'2026'|'blended'='2025';if(prior&&current){const currentWeight=Math.min(.7,current.sample/(current.sample+18));ratio=prior.ratio*(1-currentWeight)+current.ratio*currentWeight;sample=prior.sample+current.sample;source='blended'}else if(current){ratio=current.ratio;sample=current.sample;source='2026'}else if(prior){ratio=prior.ratio;sample=prior.sample;source='2025'}const multiplier=Math.max(.9,Math.min(1.1,1+(ratio-1)*.35));return{multiplier,ratio,sample,source}}

function roleMultiplier(p:string,r?:number){if(!r||r<=1)return 1;if(p==='QB')return r===2?.35:.1;if(['RB','WR','TE'].includes(p))return r===2?.84:r===3?.64:.5;if(['DL','DE','DT','LB','DB','CB','S'].includes(p))return r===2?.78:.58;return r===2?.8:.6}
function unavailableStatus(s:string){return /injured reserve|\bir\b|pup|suspend|reserve\/|non-football injury|out/.test(s.toLowerCase())}

function projectPlayer(player:RosterPlayer,s25:CsvRow[],s26:CsvRow[],roster:CsvRow[],depthRows:CsvRow[],schedule:CsvRow[]):Projection{
 const name=player.name??'Unknown player',position=(player.position??'').toUpperCase(),team=(player.nflTeam??'').toUpperCase(),historical=buildSamples(s25,player),current=buildSamples(s26,player),reasons:string[]=[`Fantasy scoring uses the AMD FFL ${AMDFFL_SCORING_VERSION} league rules.`],hs=historical.filter(s=>s.points>0||['QB','RB','WR','TE','K'].includes(position)),recent=hs.slice(-6).map(s=>s.points),season=hs.map(s=>s.points);let baseline=season.length?avg(season)*.45+avg(recent)*.55:0;
 if(season.length)reasons.push(`2025 baseline uses ${season.length} regular-season games with extra weight on the final six.`);else reasons.push('No usable 2025 weekly scoring sample was found; projection confidence is limited.');
 if(current.length){const ca=avg(current.map(s=>s.points)),w=Math.min(.8,.15+current.length*.11);baseline=baseline?baseline*(1-w)+ca*w:ca;reasons.push(`${current.length} 2026 game${current.length===1?'':'s'} now contribute ${Math.round(w*100)}% of the performance baseline.`)}
 const rm=roster.find(r=>normalizeName(displayName(r))===normalizeName(name));let confidence=season.length>=10?.72:season.length>=5?.6:season.length?.48:.28,status='';if(current.length>=3)confidence+=.08;
 if(rm){confidence+=.08;const ct=(rm.team||rm.team_abbr||rm.recent_team||'').toUpperCase();if(ct&&team&&ct!==team){confidence-=.08;reasons.push(`Current public roster data lists ${ct}, while RTSports lists ${team}; role/team transition lowers confidence.`)}else reasons.push('Current public roster context matches the synchronized RTSports player identity/team.');status=rm.status_description||rm.status||'';if(status)reasons.push(`Current roster status: ${status}.`)}else reasons.push('No current nflverse roster match was found; availability context is incomplete.');
 const d=depthContext(player,depthRows);if(d.depthRank){const mult=roleMultiplier(position,d.depthRank);if(mult!==1&&baseline>0)baseline*=mult;confidence+=d.depthRank===1?.06:-.03;reasons.push(`Latest public depth chart lists ${name} at ${d.depthSlot??position} rank ${d.depthRank}${d.depthDate?` as of ${d.depthDate}`:''}.`);if(mult<1)reasons.push(`Role adjustment applies a ${Math.round((1-mult)*100)}% opportunity discount for current depth position.`)}else reasons.push('No current depth-chart rank was matched; role confidence is unchanged.');
 const game=nextGame(team,schedule);if(game?.opponent){reasons.push(`Next scheduled opponent is ${game.opponent}${game.gameDate?` on ${game.gameDate}`:''} (${game.homeAway}).`);const matchup=matchupContext(game.opponent,position,s25,s26);if(matchup&&baseline>0){baseline*=matchup.multiplier;const pct=Math.round((matchup.multiplier-1)*100);const allowed=Math.round((matchup.ratio-1)*100);reasons.push(`${game.opponent} has allowed ${Math.abs(allowed)}% ${allowed>=0?'more':'fewer'} ${normalizedPosition(position)} AMD FFL points per player-game than league average across the available ${matchup.source} sample; Fantasy Edge applies a capped ${pct>=0?'+':''}${pct}% matchup adjustment.`);if(matchup.source==='2025')confidence-=.02;else confidence+=.01}}
 if(status&&unavailableStatus(status)){baseline=0;confidence=Math.max(confidence,.9);reasons.push('Current roster status indicates the player is unavailable, so the active-week projection is zeroed until status changes.')}
 if(position==='HC'){baseline=0;confidence=.15;reasons.push('AMD FFL head-coach scoring is known, but publishing an HC projection requires a team-result and margin-of-victory model; that model is not active yet.')}
 return{playerKey:playerKey(name,position),name,position,team,projection:baseline>0?Number(baseline.toFixed(2)):null,confidence:Math.max(.05,Math.min(.95,Number(confidence.toFixed(2)))),trend:trendFor(current.length>=4?current:historical),reasons,sourceGames:historical.length+current.length,depthRank:d.depthRank,opponent:game?.opponent}
}

async function latestRoster(db:D1Database){const r=await db.prepare(`SELECT roster_json FROM roster_syncs ORDER BY id DESC LIMIT 1`).first<{roster_json:string}>();if(!r?.roster_json)return[];try{return JSON.parse(r.roster_json) as RosterPlayer[]}catch{return[]}}

export async function refreshIntelligence(env:IntelligenceEnv){await ensureIntelligenceSchema(env.DB);const started=new Date().toISOString(),run=await env.DB.prepare(`INSERT INTO intelligence_runs (started_at,status) VALUES (?,'running')`).bind(started).run(),runId=Number(run.meta.last_row_id??0);try{const roster=await latestRoster(env.DB);if(!roster.length)throw new Error('No synchronized RTSports roster is available yet.');const [s25,s26,r26,d26,schedule]=await Promise.all([fetchCsv(`${NFLVERSE}/stats_player/stats_player_week_2025.csv`),optionalCsv(`${NFLVERSE}/stats_player/stats_player_week_2026.csv`),optionalCsv(`${NFLVERSE}/rosters/roster_2026.csv`),optionalCsv(`${NFLVERSE}/depth_charts/depth_charts_2026.csv`),optionalCsv(SCHEDULE_URL)]),projections=roster.map(p=>projectPlayer(p,s25,s26,r26,d26,schedule)),now=new Date().toISOString(),stmts:D1PreparedStatement[]=[];for(const p of projections){stmts.push(env.DB.prepare(`INSERT INTO player_intelligence (player_key,display_name,position,nfl_team,projection,confidence,trend,reasons_json,source_games,model_version,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(player_key) DO UPDATE SET display_name=excluded.display_name,position=excluded.position,nfl_team=excluded.nfl_team,projection=excluded.projection,confidence=excluded.confidence,trend=excluded.trend,reasons_json=excluded.reasons_json,source_games=excluded.source_games,model_version=excluded.model_version,updated_at=excluded.updated_at`).bind(p.playerKey,p.name,p.position,p.team,p.projection,p.confidence,p.trend,JSON.stringify(p.reasons),p.sourceGames,MODEL_VERSION,now));stmts.push(env.DB.prepare(`INSERT INTO projection_snapshots (run_id,player_key,display_name,position,nfl_team,projection,confidence,trend,reasons_json,model_version,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).bind(runId,p.playerKey,p.name,p.position,p.team,p.projection,p.confidence,p.trend,JSON.stringify(p.reasons),MODEL_VERSION,now))}for(let i=0;i<stmts.length;i+=80)await env.DB.batch(stmts.slice(i,i+80));const summary={stats2025Rows:s25.length,stats2026Rows:s26.length,roster2026Rows:r26.length,depth2026Rows:d26.length,scheduleRows:schedule.length,scoringMode:'league',scoringVersion:AMDFFL_SCORING_VERSION,matchupModel:'defense-v-position capped +/-10%',scoreCache:'row-position',modelVersion:MODEL_VERSION};await env.DB.prepare(`UPDATE intelligence_runs SET completed_at=?,status='success',source_summary=?,player_count=?,message=? WHERE id=?`).bind(now,JSON.stringify(summary),projections.length,'Projection refresh completed with AMD FFL league scoring.',runId).run();return{ok:true,runId,playerCount:projections.length,sourceSummary:summary,updatedAt:now}}catch(error){const message=error instanceof Error?error.message:String(error);await env.DB.prepare(`UPDATE intelligence_runs SET completed_at=?,status='failed',message=? WHERE id=?`).bind(new Date().toISOString(),message,runId).run();return{ok:false,runId,error:message}}}

export async function getLatestIntelligence(db:D1Database){await ensureIntelligenceSchema(db);const run=await db.prepare(`SELECT id,started_at,completed_at,status,source_summary,player_count,message FROM intelligence_runs ORDER BY id DESC LIMIT 1`).first<Record<string,unknown>>(),result=await db.prepare(`SELECT player_key,display_name,position,nfl_team,projection,confidence,trend,reasons_json,source_games,model_version,updated_at FROM player_intelligence ORDER BY position,projection DESC`).all<Record<string,unknown>>();return{run:run?{...run,source_summary:run.source_summary?JSON.parse(String(run.source_summary)):null}:null,players:result.results.map(r=>({playerKey:r.player_key,name:r.display_name,position:r.position,team:r.nfl_team,projection:r.projection,confidence:r.confidence,trend:r.trend,reasons:JSON.parse(String(r.reasons_json??'[]')),sourceGames:r.source_games,modelVersion:r.model_version,updatedAt:r.updated_at}))}}
