type RosterPlayer = {
  id?: number;
  name?: string;
  position?: string;
  rosterGroup?: string;
  lineupSlot?: string;
  injury?: string | null;
  projection?: number | null;
  averagePoints?: number | null;
};

type SlotRule = { slot: string; count: number; eligiblePositions: string[] };
type RulesSource = 'imported' | 'roster-derived' | 'fallback';
type Candidate = { player: RosterPlayer; score: number; confidence: number; reasons: string[]; playerKey: string };
type LineupItem = { slot: string; player: RosterPlayer; score: number; confidence: number; reasons: string[] };
type Alternative = { kind: 'safer-floor' | 'upside' | 'league-history'; label: string; slot: string; start: RosterPlayer; bench: RosterPlayer; projectedDelta: number; confidence: number; explanation: string };

const DEFAULT_RULES: SlotRule[] = [
  { slot: 'QB', count: 1, eligiblePositions: ['QB'] }, { slot: 'RB', count: 1, eligiblePositions: ['RB'] }, { slot: 'WR', count: 2, eligiblePositions: ['WR'] }, { slot: 'TE', count: 1, eligiblePositions: ['TE'] }, { slot: 'HC', count: 1, eligiblePositions: ['HC'] }, { slot: 'K', count: 1, eligiblePositions: ['K'] }, { slot: 'DL', count: 2, eligiblePositions: ['DL'] }, { slot: 'LB', count: 2, eligiblePositions: ['LB'] }, { slot: 'DB', count: 2, eligiblePositions: ['DB'] }, { slot: 'FLEX', count: 2, eligiblePositions: ['RB', 'WR'] }, { slot: 'IDP FLEX', count: 1, eligiblePositions: ['DL', 'LB', 'DB'] },
];
const KNOWN_POSITIONS = ['QB', 'RB', 'WR', 'TE', 'K', 'DL', 'LB', 'DB', 'HC'] as const;
const normalizeName = (value = '') => value.toLowerCase().replace(/\b(jr|sr|ii|iii|iv)\.?\b/g, '').replace(/[^a-z0-9]/g, '');
const normalizeSlot = (value = '') => value.toUpperCase().replace(/[^A-Z0-9/]+/g, ' ').trim();
const playerKey = (name = '', position = '') => `${normalizeName(name)}:${position.toUpperCase()}`;
const unavailable = (player: RosterPlayer) => player.rosterGroup === 'ir' || /^(IR|O)$/i.test(player.injury ?? '');
function parseCount(value: unknown) { if (typeof value === 'number' && Number.isFinite(value)) return Math.max(0, Math.round(value)); const match = String(value ?? '').match(/\b(\d+)\b/); return match ? Math.max(0, Number(match[1])) : null; }
function positionsMentioned(label: string) { const upper = normalizeSlot(label); return KNOWN_POSITIONS.filter(position => new RegExp(`(^|[^A-Z])${position}([^A-Z]|$)`).test(upper)); }
function inferSlot(label: string, key: string): SlotRule | null {
  const haystack = `${label} ${key}`.toLowerCase(); const countMatch = haystack.match(/(?:start|starter|starting|minimum|min|max)?\s*(\d+)\s*(qb|quarterback|rb|running back|wr|wide receiver|te|tight end|k|kicker|dl|defensive line|lb|linebacker|db|defensive back|hc|head coach)/i);
  const patterns: Array<[RegExp,string,string[]]> = [[/(quarterback|\bqb\b)/,'QB',['QB']], [/(running back|\brb\b)/,'RB',['RB']], [/(wide receiver|\bwr\b)/,'WR',['WR']], [/(tight end|\bte\b)/,'TE',['TE']], [/(head coach|\bhc\b)/,'HC',['HC']], [/(kicker|\bk\b)/,'K',['K']], [/(defensive line|\bdl\b)/,'DL',['DL']], [/(linebacker|\blb\b)/,'LB',['LB']], [/(defensive back|\bdb\b)/,'DB',['DB']]];
  if (/idp.*flex|flex.*idp/.test(haystack)) return { slot:'IDP FLEX', count:1, eligiblePositions:['DL','LB','DB'] };
  if (/flex/.test(haystack)) { const eligible=positionsMentioned(haystack).filter(p=>['QB','RB','WR','TE'].includes(p)); return {slot:'FLEX',count:1,eligiblePositions:eligible.length?eligible:['RB','WR']}; }
  for (const [pattern,slot,eligiblePositions] of patterns) if(pattern.test(haystack)) return {slot,count:countMatch?Number(countMatch[1]):1,eligiblePositions}; return null;
}
function ruleFromRosterSlot(label:string):Omit<SlotRule,'count'>|null { const normalized=normalizeSlot(label); if(!normalized)return null; const explicit=positionsMentioned(normalized); const idp=normalized.includes('FLEX')&&(normalized.includes('IDP')||normalized.includes('DEF')); if(idp){const d=explicit.filter(p=>['DL','LB','DB'].includes(p));return{slot:label,eligiblePositions:d.length?d:['DL','LB','DB']};} if(normalized.includes('FLEX')||normalized.includes('/')){const o=explicit.filter(p=>['QB','RB','WR','TE'].includes(p));if(o.length)return{slot:label,eligiblePositions:o};if(normalized.includes('FLEX'))return{slot:label,eligiblePositions:['RB','WR']};} for(const p of KNOWN_POSITIONS)if(normalized===p||normalized.startsWith(`${p} `))return{slot:label,eligiblePositions:[p]};return null; }
function deriveRulesFromRoster(roster:RosterPlayer[]){const grouped=new Map<string,SlotRule>();for(const player of roster.filter(x=>x.rosterGroup==='starter')){const label=player.lineupSlot?.trim();if(!label)continue;const inferred=ruleFromRosterSlot(label);if(!inferred)continue;const key=`${normalizeSlot(inferred.slot)}|${inferred.eligiblePositions.join(',')}`;const existing=grouped.get(key);if(existing)existing.count++;else grouped.set(key,{...inferred,count:1});}return[...grouped.values()];}
async function deriveRules(db:D1Database,roster:RosterPlayer[]):Promise<{rules:SlotRule[];source:RulesSource}>{const latest=await db.prepare(`SELECT id FROM league_config_syncs ORDER BY id DESC LIMIT 1`).first<{id:number}>();if(latest?.id){const rows=await db.prepare(`SELECT rule_key,label,value_json FROM league_rules WHERE config_sync_id=? AND category='lineup' ORDER BY id`).bind(latest.id).all<Record<string,unknown>>();const bySlot=new Map<string,SlotRule>();for(const row of rows.results){const inferred=inferSlot(String(row.label??''),String(row.rule_key??''));if(!inferred)continue;const parsed=row.value_json?JSON.parse(String(row.value_json)):null;const count=parseCount(parsed);if(count!==null)inferred.count=count;if(inferred.count>0)bySlot.set(inferred.slot,inferred);}if(bySlot.size)return{rules:[...bySlot.values()],source:'imported'};}const rr=deriveRulesFromRoster(roster);const count=rr.reduce((s,r)=>s+r.count,0);const starters=roster.filter(p=>p.rosterGroup==='starter').length;if(rr.length&&count===starters)return{rules:rr,source:'roster-derived'};return{rules:DEFAULT_RULES,source:'fallback'};}
function scoreFor(player:RosterPlayer,intel:Map<string,Record<string,unknown>>){const modeled=intel.get(playerKey(player.name,player.position));return modeled?.projection!==null&&modeled?.projection!==undefined?Number(modeled.projection):Number(player.projection??player.averagePoints??0);}
function confidenceFor(player:RosterPlayer,intel:Map<string,Record<string,unknown>>){return Number(intel.get(playerKey(player.name,player.position))?.confidence??.35);}
function ruleForSlot(slot:string,rules:SlotRule[]){const n=normalizeSlot(slot);return rules.find(r=>normalizeSlot(r.slot)===n);}
function slotLooksLike(player:RosterPlayer,slot:string){const current=normalizeSlot(player.lineupSlot??'');const target=normalizeSlot(slot);if(!current||!target)return false;if(current===target)return true;if(target.includes('FLEX'))return current.includes('FLEX')&&(target.includes('IDP')===current.includes('IDP'));return current.startsWith(target);}
function buildLegalChanges(starts:LineupItem[],benched:RosterPlayer[],rules:SlotRule[],intel:Map<string,Record<string,unknown>>){const remaining=[...benched];const changes:Array<{start:RosterPlayer;bench:RosterPlayer;slot:string;projectedGain:number;confidence:number}>=[];for(const start of starts){const rule=ruleForSlot(start.slot,rules);if(!rule)continue;const eligible=new Set(rule.eligiblePositions.map(p=>p.toUpperCase()));const legal=remaining.filter(p=>eligible.has((p.position??'').toUpperCase()));if(!legal.length)continue;const same=legal.filter(p=>slotLooksLike(p,start.slot));const pool=same.length?same:legal;const bench=[...pool].sort((a,b)=>scoreFor(a,intel)-scoreFor(b,intel))[0];const idx=remaining.findIndex(p=>playerKey(p.name,p.position)===playerKey(bench.name,bench.position));if(idx>=0)remaining.splice(idx,1);const gain=Number((start.score-scoreFor(bench,intel)).toFixed(2));if(gain>0)changes.push({start:start.player,bench,slot:start.slot,projectedGain:gain,confidence:start.confidence});}return changes;}
function buildAlternatives(lineup:LineupItem[],candidates:Candidate[],rules:SlotRule[],intel:Map<string,Record<string,unknown>>):Alternative[]{const used=new Set(lineup.map(x=>playerKey(x.player.name,x.player.position)));const out:Alternative[]=[];for(const incumbent of lineup){const rule=ruleForSlot(incumbent.slot,rules);if(!rule)continue;const eligible=new Set(rule.eligiblePositions.map(p=>p.toUpperCase()));const legal=candidates.filter(c=>!used.has(c.playerKey)&&eligible.has((c.player.position??'').toUpperCase())&&c.score>0);if(!legal.length)continue;const safer=[...legal].filter(c=>c.confidence>=incumbent.confidence+.08&&c.score>=incumbent.score*.85).sort((a,b)=>b.confidence-a.confidence)[0];if(safer)out.push({kind:'safer-floor',label:'Safer floor',slot:incumbent.slot,start:safer.player,bench:incumbent.player,projectedDelta:Number((safer.score-incumbent.score).toFixed(2)),confidence:safer.confidence,explanation:`${safer.player.name} gives up little modeled scoring for a stronger confidence profile in this legal ${incumbent.slot} slot.`});const upside=[...legal].filter(c=>c.confidence<incumbent.confidence&&c.score>=incumbent.score*.9).sort((a,b)=>b.score-a.score)[0];if(upside)out.push({kind:'upside',label:'Upside alternative',slot:incumbent.slot,start:upside.player,bench:incumbent.player,projectedDelta:Number((upside.score-incumbent.score).toFixed(2)),confidence:upside.confidence,explanation:`${upside.player.name} stays within 10% of the primary projection while carrying more uncertainty; consider this only when chasing ceiling.`});}return out.sort((a,b)=>Math.abs(b.projectedDelta)-Math.abs(a.projectedDelta)).slice(0,5);}
export async function getOptimizedLineup(db:D1Database){const rosterRow=await db.prepare(`SELECT roster_json,synced_at FROM roster_syncs ORDER BY id DESC LIMIT 1`).first<{roster_json:string;synced_at:string}>();if(!rosterRow?.roster_json)return{available:false,reason:'No synchronized roster.'};const roster=JSON.parse(rosterRow.roster_json)as RosterPlayer[];const intelligence=await db.prepare(`SELECT player_key,projection,confidence,reasons_json FROM player_intelligence`).all<Record<string,unknown>>();const intel=new Map(intelligence.results.map(row=>[String(row.player_key),row]));const candidates:Candidate[]=roster.filter(p=>!unavailable(p)).map(player=>{const key=playerKey(player.name,player.position);const modeled=intel.get(key);const score=modeled?.projection!==null&&modeled?.projection!==undefined?Number(modeled.projection):Number(player.projection??player.averagePoints??0);return{player,score,confidence:confidenceFor(player,intel),reasons:modeled?.reasons_json?JSON.parse(String(modeled.reasons_json)):[],playerKey:key};});const{rules,source}=await deriveRules(db,roster);const used=new Set<string>();const lineup:LineupItem[]=[];for(const rule of rules){const eligible=new Set(rule.eligiblePositions.map(p=>p.toUpperCase()));const selected=candidates.filter(c=>eligible.has((c.player.position??'').toUpperCase())&&!used.has(c.playerKey)).sort((a,b)=>b.score-a.score).slice(0,rule.count);for(const c of selected){used.add(c.playerKey);lineup.push({slot:rule.slot,player:c.player,score:c.score,confidence:c.confidence,reasons:c.reasons});}}const current=new Set(roster.filter(p=>p.rosterGroup==='starter').map(p=>playerKey(p.name,p.position)));const recommended=new Set(lineup.map(i=>playerKey(i.player.name,i.player.position)));const starts=lineup.filter(i=>!current.has(playerKey(i.player.name,i.player.position)));const benched=roster.filter(p=>p.rosterGroup==='starter'&&!recommended.has(playerKey(p.name,p.position)));const changes=buildLegalChanges(starts,benched,rules,intel);const alternatives=buildAlternatives(lineup,candidates,rules,intel);return{available:true,rulesSource:source,rules,rosterSyncedAt:rosterRow.synced_at,projectedPoints:Number(lineup.reduce((s,i)=>s+i.score,0).toFixed(2)),lineup,changes,alternatives};}
